name: Changelog Generator
on:
  push:
    branches:
      - master
jobs:
  generate-my-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "17.x"

      - name: Install auto-changelog
        run: |
          npm i auto-changelog

      - name: Run auto-changelog to generate changelog
        run: |
          npm run changelog v0.0.2
          git tag -n

      - name: Save - Commit and push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "changelog.md" || exit 0
          git push
