name: Changelog Generator
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  generate-my-changelog:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "17.x"

      - name: Install auto-changelog
        run: |
          npm i auto-changelog

      - name: Run auto-changelog to generate changelog
        run: |
          npm run changelog $RELEASE_VERSION
          git tag -n
        #  echo $RELEASE_VERSION
        #  echo ${{ env.RELEASE_VERSION }}

      - name: Save - Commit and push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "changelog-${timestamp}" || exit 0
          git push origin HEAD:master